name: default
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cripser
  - itertools
  - jupyterlab
  - matplotlib
  - networkx
  - numba
  - numpy
  - persim
  - python
  - seaborn
  - skimage
  - scipy
  - warnings
