'''
Basin Hierarchy Tree class
'''

import numpy as np


class BasinHierarchyTree():
    """
    Class representing a Basin Hierarchy Tree (BHT).

    The Basin Hierarchy Tree is designed for topological data analysis, primarly for
    applying topological filters to data. 

    Attributes:
    ----------
    parent : np.array or None
        The array of parent nodes for each vertex in the tree.
    children : list of lists or None
        The list of children for each vertex in the tree.
    persistent_children : list of lists or None
        The list of children for each vertex that are relevant for persistence calculations.
    positive_pers : np.array or None
        A 1D array of vertices that have positive persistence values (excluding the root).
    birth : np.array or None
        The array containing birth times for each vertex in the BHT.
    linking_vertex : np.array or None
        An array of linking vertices that connect each vertex to its parent during persistence calculations.
    root : int or None
        The index of the root vertex in the tree.
    persistence : np.array or None
        The precomputed persistence diagram. If not already computed, it will be generated by the `get_persistence` method.

    Methods:
    -------
    __init__()
        Initializes an empty Basin Hierarchy Tree with no data.
    
    _low_pers_filter(epsilon)
        Applies a topological low-persistence filter to the tree, removing cycles with persistence lower than `epsilon`.

    _lpf_size_filter(epsilon, size_gap=[0, np.inf])
        Filters basins based on their persistence and size, applying a threshold for both persistence and size.

    filter_branch(vertex, epsilon, modified)
        Recursively filters a branch of the tree, modifying the birth times of vertices with persistence below `epsilon`.

    basin_size(vertex)
        Returns the size of a basin for a given vertex, including the vertex and all its descendants.

    get_persistence(reduced=True)
        Computes the persistence diagram for the tree, optionally returning the reduced form excluding the root's infinite interval.

    _get_BHT(with_children=False)
        Retrieves the structure of the tree, including parent-child relationships, linking vertices, and optionally children of each node.

    get_descendants(v)
        Returns all descendants of a given vertex `v`.

    descendants(v, desc)
        Recursively appends descendants of a vertex `v` to the provided list `desc`.

    """
    def __init__(self, *, recursive=True) -> None:
        self.parent = None
        self.children = None
        self.persistent_children = None
        self.positive_pers = None # 1D numpy array to store the list of vertices with positive persistence, apart from the root
        self.birth = None
        self.linking_vertex = None
        self.root = None
        self.persistence = None
        self.recursive = recursive
        self.get_descendants = self.get_descendants_recursive if recursive else self.get_descendants_iterative


    def _low_pers_filter(self, epsilon):
        """ computes topological low-persistence-filtering
        Args:
            epsilon (float): cycles having persistence below this value will be eliminated
        Returns:
            np.array: a filtered image
        """
        # print(f'''BHT:
        #       Birth: {self.birth}
        #       Parent: {self.parent}
        #       Pers_child: {self.persistent_children}
        #       Linking: {self.linking_vertex}''')
        self.epsilon = epsilon
        modified = self.birth.copy()
        for vertex in self.persistent_children[self.root]:
            self.filter_branch(vertex, self.epsilon, modified)
        return(modified)
    
    def _lpf_size_filter(self, epsilon, size_gap = [0, np.inf]):
        """
        Applies the low persistence filter considering the size of the basins.

        This method modifies the 'birth' array by filtering vertices based on persistence
        and the size of their basins. Only basins whose sizes fall within the specified 
        range (`size_gap`) and are bellow the specified threshold (`epsilon`) are processed.

        Parameters:
        ----------
        epsilon : float
            The threshold for the low persistence filter.
        size_gap : list, optional
            A two-element list specifying the minimum and maximum sizes of basins to 
            be filtered. The default range is [0, np.inf], meaning all basins are considered.

        Returns:
        -------
        modified : np.array
            A modified version of the 'birth' array, where the birth times of vertices
            within the specified size gap are updated based on their parent vertex's 
            birth time.
        """
        self.epsilon = epsilon
        modified = self.birth.copy()
        for vertex in self.persistent_children[self.root]:
            self.filter_branch_with_size(vertex, self.epsilon, modified, size_gap=size_gap)
        return(modified)
    
        
    def filter_branch(self, vertex, epsilon, modified):
        """
        Recursively filters branches in the Basin Hierarchy Tree (BHT) based on persistence.

        Given a `vertex`, this method modifies the `modified` array by eliminating classes 
        in the branch of the vertex whose positive persistence is lower than a threshold 
        `epsilon`. If the persistence of a vertex is greater than or equal to `epsilon`, 
        the function proceeds to filter its children recursively.

        Parameters:
        ----------
        vertex : int
            The index of the vertex in the BHT to start filtering from.
        epsilon : float
            The persistence threshold. Branches with persistence lower than this value 
            will be filtered.
        modified : np.array
            The array that will be updated during the filtering process, where filtered 
            vertices have their birth times replaced by their linking vertex's birth time.
        
        Returns:
        -------
        None
        """
        linking_vertex = self.linking_vertex[vertex]
        persistence = self.birth[linking_vertex] - self.birth[vertex]
        if  0 < persistence < epsilon:
            modified[np.array(self.get_descendants(vertex))] = self.birth[linking_vertex]
        elif persistence >= epsilon:
            for child_vertex in self.persistent_children[vertex]:
                self.filter_branch(child_vertex, epsilon, modified)

    
    def filter_branch_with_size(self, vertex, epsilon, modified, *, size_gap=[0,np.inf]):
        """
        filter branch considering basin size
        """
        linking_vertex = self.linking_vertex[vertex]
        persistence = self.birth[linking_vertex] - self.birth[vertex]
        if  0 < persistence < epsilon:
            desc = np.array(self.get_descendants(vertex))
            size = len(desc)
            if size_gap[0] <= size: 
                if size <= size_gap[1]:
                    modified[desc] = self.birth[linking_vertex]
                else:
                    for child_vertex in self.persistent_children[vertex]:
                        self.filter_branch_with_size(child_vertex, epsilon, modified, size_gap=size_gap)
        elif persistence >= epsilon:
            for child_vertex in self.persistent_children[vertex]:
                self.filter_branch_with_size(child_vertex, epsilon, modified, size_gap=size_gap)


    def basin_size(self, vertex):
        """
        Returns the size of the basin associated with a given `vertex`.

        A basin is composed of the vertex itself and all of its descendants in the BHT.

        Parameters:
        ----------
        vertex : int
            The index of the vertex for which the basin size is calculated.

        Returns:
        -------
        int
            The size of the basin, which is the number of the vertex's descendants plus the vertex itself.
        """
        return len(self.get_descendants(vertex))
    

    def get_persistence(self, *, reduced=True):
        """
        Computes the persistence diagram for the Basin Hierarchy Tree (BHT).

        The persistence diagram consists of tuples representing (birth, death, birth_location, death_location, basin_size).
        If `reduced` is False, the root's infinite interval is also included in the diagram.

        Parameters:
        ----------
        reduced : bool, optional
            If True, the diagram excludes the root's infinite interval (default is True).

        Returns:
        -------
        np.array
            The computed persistence diagram as an array, with each entry corresponding to 
            a persistence pair (birth, death, birth_location, death_location, basin_size).
        """

        # if not self.persistence is None:
        #     return self.persistence

        #(birth, death, birth_location, death_location, basin_size)
        self.persistence = np.array([[self.birth[v], self.birth[self.linking_vertex[v]], v, self.linking_vertex[v], self.basin_size(v)] for v in self.positive_pers])

        if reduced==False:
            permanent_interval = np.array([[self.birth[self.root], np.inf, self.root, -1, np.inf]])
            self.persistence = np.concatenate((self.persistence, permanent_interval))
        
        return self.persistence
    
    def _get_BHT(self, *, with_children=False):
        """
        Retrieves the Basin Hierarchy Tree (BHT) structure.

        Returns the list of parents, linking vertices, and the root of the tree. If `with_children` 
        is True, also returns the list of children for each vertex in the tree.

        Parameters:
        ----------
        with_children : bool, optional
            If True, the children of each node are returned in the output (default is False).

        Returns:
        -------
        tuple
            A tuple containing (parents, linking_vertex, root). If `with_children` is True, 
            the children of each node are also included.
        """
        if self.children == None:
            print("BHT is empty")
            return None
        if with_children:
            return self.parent, self.linking_vertex, self.root, [list(x) for x in self.children]
        return self.parent, self.linking_vertex, self.root
    

    def get_descendants_recursive(self, v):
        """
        Returns a list of all descendants of a given vertex `v`.

        Parameters:
        ----------
        v : int
            The vertex for which to retrieve descendants.

        Returns:
        -------
        list
            A list of vertex indices that are descendants of `v`.
        """
        desc = []  
        self.descendants(v, desc)  
        return desc


    def descendants(self, v, desc):
        """
        Recursively collects all descendants of a vertex `v` into the list `desc`.

        Parameters:
        ----------
        v : int
            The current vertex being processed.
        desc : list
            A list that accumulates the descendants of `v`.
        
        Returns:
        -------
        None
        """
        desc.append(v)  # Append the current node
        for child in self.children[v]:  # Use a loop to iterate over the children
            self.descendants(child, desc)  # Recursively find descendants


    def get_descendants_iterative(self, v):
        """
        Iteratively collects all descendants of a vertex `v`.

        Parameters:
        ----------
        v : int
            The vertex for which to retrieve descendants.

        Returns:
        -------
        list
            A list of vertex indices that are descendants of `v`.
        """
        descendants = []
        stack = [v]  # Stack to manage the traversal (DFS)
        
        while stack:
            current = stack.pop()  # Process the next vertex
            descendants.append(current)  # Add the current vertex to the list
            stack.extend(self.children[current])  # Add children to the stack for further exploration
        
        return descendants
